# Generated by Django 6.0.3 on 2026-05-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborationscompany',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Collaborations Companies'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-created_at']},
        ),
    ]
