# Generated by Django 6.0.3 on 2026-05-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_socialmediaservices_alter_collaborationscompany_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.ImageField(upload_to='social_media_icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Social Media Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SocialMediaServices',
        ),
        migrations.AlterField(
            model_name='collaborationscompany',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
