# Generated by Django 6.0.3 on 2026-05-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_socialmediaservice_delete_socialmediaservices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationscompany',
            name='name_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collaborationscompany',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='contact_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='contact_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='details_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='details_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='name_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaservice',
            name='name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaservice',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
