# Generated by Django 6.0.3 on 2026-05-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_socialmediaservices'),
        ('package', '0005_collaborationscompany_name_bn_and_more'),
    ]

    operations = [
    ]
