# Generated by Django 6.0.3 on 2026-06-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_merge_20260518_0638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMediaServices',
        ),
        migrations.AddField(
            model_name='socialmediaservice',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaservice',
            name='details_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaservice',
            name='details_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaservice',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='collaborationscompany',
            name='name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collaborationscompany',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='contact_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='contact_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='details_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='details_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
