# Generated by Django 6.0.3 on 2026-06-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_delete_socialmediaservices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationscompany',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborationscompany',
            name='details_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborationscompany',
            name='details_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
