# Generated by Django 6.0.3 on 2026-04-26 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='accessory_categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Accessory Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='medical_accessories/')),
                ('details', models.TextField()),
                ('contact_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='medical_accessories.accessorycategory')),
            ],
            options={
                'verbose_name_plural': 'Medical Accessories',
                'ordering': ['-created_at'],
            },
        ),
    ]
