# Generated by Django 6.0.3 on 2026-05-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_accessories', '0002_alter_accessorycategory_id_alter_medicalaccessory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorycategory',
            name='name_bn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accessorycategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalaccessory',
            name='contact_details_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalaccessory',
            name='contact_details_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalaccessory',
            name='details_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalaccessory',
            name='details_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalaccessory',
            name='name_bn',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='medicalaccessory',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='accessorycategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicalaccessory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
