# Generated by Django 6.0.3 on 2026-04-15 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['id']},
        ),
    ]
