# Generated by Django 6.0.3 on 2026-04-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0002_alter_doctor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_icons/'),
        ),
    ]
