# Generated by Django 6.0.3 on 2026-04-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0003_subcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='contact_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_sedule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
