# Generated by Django 6.0.3 on 2026-04-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0004_doctor_contact_details_doctor_doctor_sedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='logo',
        ),
    ]
