# Generated by Django 6.0.3 on 2026-04-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0005_remove_hospital_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='contact_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
