# Generated by Django 6.0.3 on 2026-05-03 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0006_hospital_address_hospital_contact_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['id']},
        ),
    ]
