# Generated by Django 6.0.3 on 2026-05-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0007_alter_servicecategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
