# Generated by Django 6.0.3 on 2026-05-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0008_doctor_doctor_fees_doctor_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_fees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
