# Generated by Django 6.0.3 on 2026-05-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0009_alter_doctor_doctor_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
