# Generated by Django 6.0.3 on 2026-05-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0010_remove_payment_booking_delete_booking_delete_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-id']},
        ),
    ]
