# Generated by Django 6.0.3 on 2026-05-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0011_alter_doctor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='service_banners/'),
        ),
    ]
