# Generated by Django 4.2.11 on 2026-05-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("popular_service", "0011_alter_doctor_options"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name="doctor",
        #     name="id",
        #     field=models.AutoField(
        #         auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="hospital",
        #     name="id",
        #     field=models.AutoField(
        #         auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="servicecategory",
        #     name="id",
        #     field=models.AutoField(
        #         auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="subcategory",
        #     name="id",
        #     field=models.AutoField(
        #         auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
        #     ),
        # ),
    ]
