# Generated by Django 6.0.3 on 2026-05-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0012_alter_doctor_id_alter_hospital_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='service_banners/'),
        ),
    ]
