# Generated by Django 6.0.3 on 2026-05-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0012_servicecategory_banner'),
        ('popular_service', '0014_doctor_contact_details_bn_doctor_contact_details_en_and_more'),
    ]

    operations = [
    ]
