# Generated by Django 6.0.3 on 2026-05-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0015_merge_20260518_0638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['id']},
        ),
    ]
