# Generated by Django 6.0.3 on 2026-05-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0017_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['id']},
        ),
    ]
