# Generated by Django 6.0.3 on 2026-05-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0018_alter_subcategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='contact_details_bn',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='contact_details_en',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_fees_bn',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_fees_en',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_sedule_bn',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_sedule_en',
        ),
    ]
