# Generated by Django 6.0.3 on 2026-05-20 07:51

from django.db import migrations, models

def migrate_data(apps, schema_editor):
    Doctor = apps.get_model('popular_service', 'Doctor')
    for doctor in Doctor.objects.all():
        if doctor.subcategory:
            doctor.subcategories.add(doctor.subcategory)

def reverse_migrate_data(apps, schema_editor):
    Doctor = apps.get_model('popular_service', 'Doctor')
    for doctor in Doctor.objects.all():
        first_subcategory = doctor.subcategories.first()
        if first_subcategory:
            doctor.subcategory = first_subcategory
            doctor.save()

class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0019_remove_doctor_contact_details_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='subcategories',
            field=models.ManyToManyField(related_name='doctors', to='popular_service.subcategory'),
        ),
        migrations.RunPython(migrate_data, reverse_migrate_data),
        migrations.RemoveField(
            model_name='doctor',
            name='subcategory',
        ),
    ]
