# Generated by Django 6.0.3 on 2026-06-01 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0020_remove_doctor_subcategory_doctor_subcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='popular_service.hospital'),
        ),
    ]
