# Generated by Django 6.0.3 on 2026-06-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0021_alter_doctor_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='designation_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='designation_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
