# Generated by Django 6.0.3 on 2026-05-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top_doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='topdoctor',
            options={'ordering': ['-created_at']},
        ),
    ]
