# Generated by Django 6.0.3 on 2026-05-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_doctor', '0002_alter_booking_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topdoctor',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Consultation fees for the doctor', max_digits=10, null=True),
        ),
    ]
