# Generated by Django 6.0.3 on 2026-05-10 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0008_doctor_doctor_fees_doctor_years_of_experience'),
        ('top_doctor', '0003_topdoctor_fees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topdoctor',
            old_name='designations',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='topdoctor',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='topdoctor',
            name='fees',
        ),
        migrations.AddField(
            model_name='topdoctor',
            name='contact_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topdoctor',
            name='doctor_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topdoctor',
            name='doctor_fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='topdoctor',
            name='doctor_sedule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topdoctor',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_doctors', to='popular_service.hospital'),
        ),
        migrations.AddField(
            model_name='topdoctor',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_doctors', to='popular_service.subcategory'),
        ),
        migrations.AddField(
            model_name='topdoctor',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='topdoctor',
            name='image',
            field=models.ImageField(upload_to='doctor_images/'),
        ),
    ]
