# Generated by Django 6.0.3 on 2026-05-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_doctor', '0004_rename_designations_topdoctor_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topdoctor',
            name='doctor_fees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
