# Generated by Django 4.2.11 on 2026-05-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("top_doctor", "0006_remove_payment_booking_delete_booking_delete_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topdoctor",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
