# Generated by Django 6.0.3 on 2026-05-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_doctor', '0007_alter_topdoctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='topdoctor',
            name='contact_details_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topdoctor',
            name='contact_details_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topdoctor',
            name='designation_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topdoctor',
            name='designation_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topdoctor',
            name='doctor_details_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topdoctor',
            name='doctor_details_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topdoctor',
            name='doctor_fees_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topdoctor',
            name='doctor_fees_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topdoctor',
            name='doctor_sedule_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topdoctor',
            name='doctor_sedule_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topdoctor',
            name='name_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topdoctor',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='topdoctor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
