# Generated by Django 6.0.3 on 2026-04-07 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag', models.ImageField(upload_to='flags/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('icon', models.ImageField(upload_to='hospital_icons/')),
                ('agreement_status', models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], max_length=20)),
                ('public_hospital_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='foreign_treatments.country')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='hospital_banners/')),
                ('description', models.TextField()),
                ('contact_info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='foreign_treatments.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
