# Generated by Django 6.0.3 on 2026-04-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_treatments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='agreement_status',
            field=models.CharField(choices=[('Done', 'Done'), ('Trough Doctors', 'Trough Doctors'), ('WIP', 'WIP'), ('Pending', 'Pending')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='public_hospital_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
