# Generated by Django 6.0.3 on 2026-04-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_treatments', '0002_alter_hospital_agreement_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='agreement_status',
        ),
    ]
