# Generated by Django 6.0.3 on 2026-04-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_treatments', '0003_remove_hospital_agreement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='public_hospital_count',
        ),
        migrations.AddField(
            model_name='hospital',
            name='speciality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
