# Generated by Django 4.2.11 on 2026-05-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foreign_treatments", "0004_remove_hospital_public_hospital_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="hospitaldetail",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
