# Generated by Django 6.0.3 on 2026-05-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_treatments', '0005_alter_country_id_alter_hospital_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_bn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='name_bn',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='speciality_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='speciality_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospitaldetail',
            name='contact_info_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hospitaldetail',
            name='contact_info_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hospitaldetail',
            name='description_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hospitaldetail',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hospitaldetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
