# Generated by Django 6.0.3 on 2026-07-05 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_treatments', '0006_country_name_bn_country_name_en_hospital_name_bn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=100, null=True, unique=True)),
                ('name_bn', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_bn', models.CharField(max_length=100, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='foreign_treatments.division')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['name'],
                'unique_together': {('division', 'name'), ('division', 'name_bn'), ('division', 'name_en')},
            },
        ),
        migrations.CreateModel(
            name='BangladeshHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_id', models.PositiveIntegerField(help_text='Hospital ID from Guardian Life list.', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_bn', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bangladesh_hospital_images/')),
                ('area', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('address_en', models.TextField(blank=True, null=True)),
                ('address_bn', models.TextField(blank=True, null=True)),
                ('facilities', models.TextField(blank=True)),
                ('facilities_en', models.TextField(blank=True, null=True)),
                ('facilities_bn', models.TextField(blank=True, null=True)),
                ('contact_details', models.TextField(blank=True)),
                ('contact_details_en', models.TextField(blank=True, null=True)),
                ('contact_details_bn', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('remark_en', models.TextField(blank=True, null=True)),
                ('remark_bn', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitals', to='foreign_treatments.district')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitals', to='foreign_treatments.division')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='foreign_tre_name_1e62ab_idx'), models.Index(fields=['division'], name='foreign_tre_divisio_9de1b6_idx'), models.Index(fields=['district'], name='foreign_tre_distric_e14272_idx'), models.Index(fields=['area'], name='foreign_tre_area_25ebc4_idx'), models.Index(fields=['name_en'], name='foreign_tre_name_1e62ab_idx-en'), models.Index(fields=['name_bn'], name='foreign_tre_name_1e62ab_idx-bn')],
            },
        ),
    ]
