# Generated by Django 6.0.3 on 2026-07-05 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_treatments', '0007_division_district_bangladeshhospital'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bangladeshhospital',
            options={'ordering': ['name'], 'verbose_name': 'Bangladesh Hospital', 'verbose_name_plural': 'Bangladesh Hospitals'},
        ),
    ]
