# Generated by Django 6.0.3 on 2026-07-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_treatments', '0008_alter_bangladeshhospital_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name'], 'verbose_name': 'Bangladesh District', 'verbose_name_plural': 'Bangladesh Districts'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['name'], 'verbose_name': ' Bangladesh Division', 'verbose_name_plural': ' Bangladesh Divisions'},
        ),
    ]
