# Generated by Django 6.0.3 on 2026-07-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_treatments', '0009_alter_district_options_alter_division_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalGuardianHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_hospital_id', models.PositiveIntegerField(help_text='Hospital ID from Guardian Life list.', unique=True)),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_name_en', models.CharField(max_length=255, null=True)),
                ('hospital_name_bn', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=100)),
                ('country_en', models.CharField(max_length=100, null=True)),
                ('country_bn', models.CharField(max_length=100, null=True)),
                ('address', models.TextField()),
                ('address_en', models.TextField(null=True)),
                ('address_bn', models.TextField(null=True)),
                ('discount', models.TextField(blank=True)),
                ('discount_en', models.TextField(blank=True, null=True)),
                ('discount_bn', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_person_en', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_details', models.TextField(blank=True)),
                ('contact_details_en', models.TextField(blank=True, null=True)),
                ('contact_details_bn', models.TextField(blank=True, null=True)),
                ('cashless_facility', models.TextField(blank=True)),
                ('cashless_facility_en', models.TextField(blank=True, null=True)),
                ('cashless_facility_bn', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'international_guardian_hospitals',
                'ordering': ['hospital_name'],
            },
        ),
    ]
