# Generated by Django 6.0.3 on 2026-07-08 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_treatments', '0010_internationalguardianhospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'International Country',
                'verbose_name_plural': 'International Countries',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='internationalguardianhospital',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitals', to='foreign_treatments.internationalcountry'),
        ),
        migrations.AlterField(
            model_name='internationalguardianhospital',
            name='country_bn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospitals', to='foreign_treatments.internationalcountry'),
        ),
        migrations.AlterField(
            model_name='internationalguardianhospital',
            name='country_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospitals', to='foreign_treatments.internationalcountry'),
        ),
    ]
