# Generated by Django 6.0.3 on 2026-07-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign_treatments', '0011_internationalcountry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationalguardianhospital',
            name='country_bn',
        ),
        migrations.RemoveField(
            model_name='internationalguardianhospital',
            name='country_en',
        ),
        migrations.AddField(
            model_name='internationalcountry',
            name='name_bn',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='internationalcountry',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
