# Generated by Django 6.0.3 on 2026-04-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
