# Generated by Django 6.0.3 on 2026-06-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_district_bn_user_district_en_user_name_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_14h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_2h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
