# Generated by Django 6.0.3 on 2026-06-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_recorddocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorddocuments',
            name='document_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
