# Generated by Django 6.0.3 on 2026-04-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload image for Slider One', upload_to='sliders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slider One',
                'verbose_name_plural': 'Slider Ones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SliderTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload image for Slider Two', upload_to='sliders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slider Two',
                'verbose_name_plural': 'Slider Twos',
                'ordering': ['-created_at'],
            },
        ),
    ]
