# Generated by Django 6.0.3 on 2026-06-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_alter_sliderone_id_alter_slidertwo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderone',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for Slider One', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sliderone',
            name='description',
            field=models.TextField(blank=True, help_text='Description for Slider One', null=True),
        ),
        migrations.AddField(
            model_name='sliderone',
            name='link',
            field=models.URLField(blank=True, help_text='Link for Slider One', null=True),
        ),
        migrations.AddField(
            model_name='sliderone',
            name='title',
            field=models.CharField(blank=True, help_text='Title for Slider One', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slidertwo',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for Slider Two', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slidertwo',
            name='description',
            field=models.TextField(blank=True, help_text='Description for Slider Two', null=True),
        ),
        migrations.AddField(
            model_name='slidertwo',
            name='link',
            field=models.URLField(blank=True, help_text='Link for Slider Two', null=True),
        ),
        migrations.AddField(
            model_name='slidertwo',
            name='title',
            field=models.CharField(blank=True, help_text='Title for Slider Two', max_length=255, null=True),
        ),
    ]
