# Generated by Django 6.0.3 on 2026-06-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0004_sliderone_alt_text_sliderone_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderone',
            name='alt_text_bn',
            field=models.CharField(blank=True, help_text='Alternative text for Slider One', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sliderone',
            name='alt_text_en',
            field=models.CharField(blank=True, help_text='Alternative text for Slider One', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sliderone',
            name='description_bn',
            field=models.TextField(blank=True, help_text='Description for Slider One', null=True),
        ),
        migrations.AddField(
            model_name='sliderone',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description for Slider One', null=True),
        ),
        migrations.AddField(
            model_name='sliderone',
            name='title_bn',
            field=models.CharField(blank=True, help_text='Title for Slider One', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sliderone',
            name='title_en',
            field=models.CharField(blank=True, help_text='Title for Slider One', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slidertwo',
            name='alt_text_bn',
            field=models.CharField(blank=True, help_text='Alternative text for Slider Two', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slidertwo',
            name='alt_text_en',
            field=models.CharField(blank=True, help_text='Alternative text for Slider Two', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slidertwo',
            name='description_bn',
            field=models.TextField(blank=True, help_text='Description for Slider Two', null=True),
        ),
        migrations.AddField(
            model_name='slidertwo',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description for Slider Two', null=True),
        ),
        migrations.AddField(
            model_name='slidertwo',
            name='title_bn',
            field=models.CharField(blank=True, help_text='Title for Slider Two', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slidertwo',
            name='title_en',
            field=models.CharField(blank=True, help_text='Title for Slider Two', max_length=255, null=True),
        ),
    ]
