# Generated by Django 6.0.3 on 2026-05-09 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='special_category_icons/')),
            ],
            options={
                'verbose_name_plural': 'Special Categories',
            },
        ),
        migrations.CreateModel(
            name='SpecialHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='doctor_images/')),
                ('designation', models.CharField(max_length=255)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('doctor_fees', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('doctor_details', models.TextField(blank=True, null=True)),
                ('doctor_sedule', models.TextField(blank=True, null=True)),
                ('contact_details', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='special_doctor.specialcategory')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='special_doctor.specialhospital')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
