# Generated by Django 6.0.3 on 2026-05-09 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_service', '0008_doctor_doctor_fees_doctor_years_of_experience'),
        ('special_doctor', '0002_specialbooking_specialpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialdoctor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_doctors', to='popular_service.subcategory'),
        ),
        migrations.AlterField(
            model_name='specialdoctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_doctors', to='popular_service.hospital'),
        ),
        migrations.DeleteModel(
            name='SpecialCategory',
        ),
        migrations.DeleteModel(
            name='SpecialHospital',
        ),
    ]
