# Generated by Django 6.0.3 on 2026-05-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_doctor', '0003_alter_specialdoctor_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialdoctor',
            old_name='category',
            new_name='subcategory',
        ),
    ]
