# Generated by Django 6.0.3 on 2026-05-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_doctor', '0005_alter_specialdoctor_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialdoctor',
            name='doctor_fees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
