# Generated by Django 6.0.3 on 2026-05-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_doctor', '0006_alter_specialdoctor_doctor_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialpayment',
            name='booking',
        ),
        migrations.DeleteModel(
            name='SpecialBooking',
        ),
        migrations.DeleteModel(
            name='SpecialPayment',
        ),
    ]
