# Generated by Django 6.0.3 on 2026-05-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_doctor', '0007_remove_specialpayment_booking_delete_specialbooking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialdoctor',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='specialdoctor',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialdoctor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
