# Generated by Django 4.2.11 on 2026-05-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "special_doctor",
            "0007_remove_specialpayment_booking_delete_specialbooking_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialdoctor",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
