# Generated by Django 6.0.3 on 2026-05-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_doctor', '0008_remove_specialdoctor_subcategory_and_more'),
        ('special_doctor', '0009_specialdoctor_contact_details_bn_and_more'),
    ]

    operations = [
    ]
