# Generated by Django 6.0.3 on 2026-06-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_doctor', '0010_merge_20260518_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialdoctor',
            name='designation_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialdoctor',
            name='designation_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialdoctor',
            name='name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialdoctor',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
