# Generated by Django 6.0.3 on 2026-05-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_quotewiserd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotewiserd',
            name='quote_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quotewiserd',
            name='quote_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quotewiserd',
            name='title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotewiserd',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quotewiserd',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
