# Generated by Django 6.0.3 on 2026-04-26 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='service_categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Medical Service Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalServiceDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='service_doctors/')),
                ('hospital', models.CharField(max_length=255)),
                ('doctor_details', models.TextField()),
                ('schedule_time', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='other_medical_service.medicalservicecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
