# Generated by Django 6.0.3 on 2026-05-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_medical_service', '0002_alter_medicalservicecategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalservicecategory',
            name='name_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalservicecategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalservicedoctor',
            name='doctor_details_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalservicedoctor',
            name='doctor_details_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalservicedoctor',
            name='hospital_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalservicedoctor',
            name='hospital_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalservicedoctor',
            name='name_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalservicedoctor',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalservicedoctor',
            name='schedule_time_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalservicedoctor',
            name='schedule_time_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalservicecategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicalservicedoctor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
